package com.dauducbach.clone.modules.chat.repository;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.r2dbc.core.DatabaseClient;
import org.springframework.r2dbc.core.RowsFetchSpec;
import reactor.core.publisher.Flux;

import java.sql.Connection;
import java.sql.DriverManager;
import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import java.util.concurrent.atomic.AtomicReference;
import java.util.function.BiFunction;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

/** Executes the SQL actually generated by the inbox repository against H2 in MySQL mode. */
class ChatConversationInboxSqlTest {
    private Connection db;

    @BeforeEach
    void setup() throws Exception {
        db = DriverManager.getConnection("jdbc:h2:mem:inbox_" + UUID.randomUUID() + ";MODE=MySQL");
        execute("CREATE TABLE conversations(id VARCHAR(64) PRIMARY KEY, conversation_type VARCHAR(16), is_dissolved BOOLEAN DEFAULT FALSE, title VARCHAR(255), last_message_seq BIGINT, last_message_id VARCHAR(64), last_message_at TIMESTAMP, created_at TIMESTAMP)");
        execute("CREATE TABLE conversation_members(conversation_id VARCHAR(64), user_id VARCHAR(64), member_role VARCHAR(16), member_status VARCHAR(16), nickname VARCHAR(255), last_read_seq BIGINT DEFAULT 0, joined_seq BIGINT DEFAULT 1, last_deleted_message_seq BIGINT, last_delivered_seq BIGINT DEFAULT 0)");
        execute("CREATE TABLE messages(id VARCHAR(64) PRIMARY KEY, conversation_id VARCHAR(64), message_seq BIGINT, sender_id VARCHAR(64), message_type VARCHAR(16), content VARCHAR(255), deleted_at TIMESTAMP)");
        execute("CREATE TABLE user_details(user_id VARCHAR(64), full_name VARCHAR(255), username VARCHAR(255))");
        execute("CREATE TABLE media(owner_id VARCHAR(64), owner_type VARCHAR(32), secure_url VARCHAR(255), url VARCHAR(255), created_at TIMESTAMP)");
        seed("empty-direct", "DIRECT", 0, "2026-10-09 11:00:00");
        seed("empty-group", "GROUP", 0, "2026-10-09 10:00:00");
        seed("text", "DIRECT", 1, "2026-10-07 11:00:00");
        seed("system", "GROUP", 1, "2026-10-07 10:00:00");
        execute("UPDATE messages SET message_type='SYSTEM' WHERE conversation_id='system'");
    }

    @AfterEach
    void close() throws Exception {
        db.close();
    }

    @Test
    void emptyConversationsDoNotConsumeInboxPageSlots() throws Exception {
        assertThat(inbox(null, null, 2)).containsExactly("text", "system");
    }

    @Test
    void cursorPageAlsoExcludesEmptyConversations() throws Exception {
        seed("older-empty", "DIRECT", 0, "2026-10-07 10:30:00");
        assertThat(inbox(Instant.parse("2026-10-07T11:00:00Z"), "text", 2)).containsExactly("system");
    }

    @Test
    void firstPersistedMessageMakesDraftConversationVisible() throws Exception {
        execute("INSERT INTO messages VALUES('first', 'empty-direct', 1, 'other', 'AUDIO', NULL, NULL)");
        execute("UPDATE conversations SET last_message_seq=1, last_message_id='first', last_message_at=TIMESTAMP '2026-10-10 12:00:00' WHERE id='empty-direct'");

        assertThat(inbox(null, null, 10)).containsExactly("empty-direct", "text", "system");
    }

    @Test
    void recalledMessageStillCountsAsMessageAndExistingDeletionBoundaryIsPreserved() throws Exception {
        execute("UPDATE messages SET deleted_at=CURRENT_TIMESTAMP, content=NULL WHERE conversation_id='text'");
        assertThat(inbox(null, null, 10)).containsExactly("text", "system");
        execute("UPDATE conversation_members SET last_deleted_message_seq=1 WHERE conversation_id='text' AND user_id='me'");
        assertThat(inbox(null, null, 10)).containsExactly("system");
    }

    @Test
    void inactiveMemberCannotSeeConversationWithMessages() throws Exception {
        execute("UPDATE conversation_members SET member_status='REMOVED' WHERE conversation_id='text' AND user_id='me'");
        assertThat(inbox(null, null, 10)).containsExactly("system");
    }

    private void seed(String id, String type, long seq, String at) throws Exception {
        execute("INSERT INTO conversations(id,conversation_type,title,last_message_seq,last_message_id,last_message_at,created_at) VALUES('" + id + "','" + type + "','" + id + "'," + seq + ","
                + (seq > 0 ? "'message-" + id + "',TIMESTAMP '" + at + "'" : "NULL,NULL") + ",TIMESTAMP '" + at + "')");
        execute("INSERT INTO conversation_members(conversation_id,user_id,member_role,member_status) VALUES('" + id + "','me','USER','ACTIVE'),('" + id + "','other','USER','ACTIVE')");
        if (seq > 0) execute("INSERT INTO messages VALUES('message-" + id + "','" + id + "'," + seq + ",'other','TEXT','hello',NULL)");
    }

    @SuppressWarnings({"rawtypes", "unchecked"})
    private List<String> inbox(Instant cursorAt, String cursorId, int limit) throws Exception {
        AtomicReference<String> capturedSql = new AtomicReference<>();
        DatabaseClient client = mock(DatabaseClient.class);
        DatabaseClient.GenericExecuteSpec spec = mock(DatabaseClient.GenericExecuteSpec.class);
        RowsFetchSpec rows = mock(RowsFetchSpec.class);
        when(client.sql(anyString())).thenAnswer(invocation -> {
            capturedSql.set(invocation.getArgument(0));
            return spec;
        });
        when(spec.bind(anyString(), any())).thenReturn(spec);
        when(spec.map(any(BiFunction.class))).thenReturn(rows);
        when(rows.all()).thenReturn(Flux.empty());
        new ChatReadRepository(client).findConversations("me", cursorAt, cursorId, limit).collectList().block();
        String sql = capturedSql.get().replace(":userId", "'me'").replace(":limit", String.valueOf(limit));
        if (cursorAt != null) sql = sql.replace(":cursorAt", "TIMESTAMP '2026-10-07 11:00:00'").replace(":cursorId", "'" + cursorId + "'");
        try (var statement = db.createStatement(); var result = statement.executeQuery(sql)) {
            List<String> ids = new ArrayList<>();
            while (result.next()) ids.add(result.getString("id"));
            return ids;
        }
    }

    private void execute(String sql) throws Exception {
        try (var statement = db.createStatement()) {
            statement.execute(sql);
        }
    }
}
