server:
  port: 8888

logging:
  config: classpath:log4j2.xml

spring:
  application:
    name: social-media
  webflux:
    base-path: /app

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 5000
      password: ${REDIS_PASSWORD}

  elasticsearch:
    uris: http://localhost:9200
    username: ${ELASTICSEARCH_USERNAME}
    password: ${ELASTICSEARCH_PASSWORD}

  r2dbc:
    url: "r2dbc:mysql://localhost:3306/ins_clone"
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    pool:
      enabled: true
      max-idle-time: 30m

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
            redirect-uri: http://localhost:8888/app/login/oauth2/code/google
            authorization-grant-type: authorization_code
            client-name: Google
          facebook:
            client-id: ${FACEBOOK_CLIENT_ID}
            client-secret: ${FACEBOOK_CLIENT_SECRET}
            scope:
              - email
              - public_profile
            redirect-uri: http://localhost:8888/app/login/oauth2/code/facebook
            authorization-grant-type: authorization_code
            client-name: Facebook
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope:
              - user:email
              - read:user
            redirect-uri: http://localhost:8888/app/login/oauth2/code/github
            authorization-grant-type: authorization_code
            client-name: GitHub

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jackson:
    serialization:
      write-dates-as-timestamps: false

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

jwt:
  signerKey: ${JWT_SIGNER_KEY}
  valid-duration: 900


#    http://localhost:8888/app/oauth2/authorization/google
#    http://localhost:8888/app/oauth2/authorization/facebook
#    http://localhost:8888/app/oauth2/authorization/github