package com.dauducbach.clone.commons.constant;

public enum UserActionType {
    REGISTRATION,
    LOGIN,
    LOGOUT,
    FORGOT_PASSWORD,
    REFRESH_TOKEN,
    NEW_POST,
    LIKE,
    LIKES,
    LIKE_OTHER_INTERACT_PEOPLE,
    COMMENT,
    COMMENTS,
    COMMENT_OTHER_INTERACT_PEOPLE,
    REPLY_COMMENT,
    LIKE_COMMENT,
    SEND_MESSAGE,
    ADD_FRIEND,
    ACCEPT_FRIEND,
    RESET_PASSWORD,
    RESET_PASSWORD_AND_USERNAME,
    WELCOME_USER,

}
